### ISSUE TITLE
blocks have a dark shadow on top of them

### ISSUE THREAD

**Issue by Dokterdrap** [sakura-ryoko/litematica#112]
hello

since the last version of litematica I have a issue with dark shadows on top and bottom of the ghostblocks in the shematic
the version I am ussing right now is "litematica-fabric-1.21.3-0.20.1". also the text for what I have to place is no longer on top so it;s underneath the minimap and I think also under other graphical things I don't know if this has something to do with litematica or with xearo minimap. I will provde a picture so you can see what I mean with the text underneath the minimap and the dark shadows. 
![2024-12-02_14 28 17](https://github.com/user-attachments/assets/d56c1c00-6e3c-4b2a-bbf8-11cd03f68d4f)
![2024-12-02_14 28 01](https://github.com/user-attachments/assets/aed63ce4-57fb-4c26-8a4f-adc797270060)

**Comment by sakura-ryoko** [comment]
I don't recall if you can move the Litematica text off hand, but I do know that you can move the Xareo's minimap.

Also, if you are in Layer mode, the "Shadows" are usually the shadows of the layers above or below the layer that your working with.  There was a change to the AO (Shadowing) of the block rendering that I was experimenting with trying to improve the compatibility with Shaders.  I do intend to see if I can make that configurable somehow, along with the "Fake Lighting" light level, because as it stands, the "Fake Lighting" is basically set to full bright 15.  The AO is effected by the ambient light levels and the Fog effects of the "Biome/Dimension" of the schematic world, and blocks that would otherwise be stacked directly on top of the viewed layer, or below it.  In previous versions, the AO calculations did not take those things into consideration.

Like I said, I think it should be configurable somehow, like Disable / (Old Style) / (New Style) or something; and give people a "Fake Lighting brightness Slider" .

You can say it's something on my TODO list.

**Comment by sakura-ryoko** [comment]
Try this with the `sakura.2` build.  I have enabled a toggle-able AO rendering switch (Off by default) to deal with the shadows.

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/litematica/releases/tag/1.21.3-0.20.2-sakura.2
