### ISSUE TITLE
Error and lag when on any layer mode besides "All"

### ISSUE THREAD

**Issue by JermsyBoy** [sakura-ryoko/litematica#6]
I've noticed an issue on the latest version (may have been on previous versions too but just didn't notice) where as soon as I switch the layer mode to any setting either than "All" the game log gets spammed with errors and it starts to lag the game like crazy. 

https://mclo.gs/mWuv5T7

**Comment by sakura-ryoko** [comment]
If you are trying to render a "large" build you may need to enable "overlayReducedInnerSides" so the game doesn't struggle with the rendering.  In most cases those Rendering errors can be ignored, because it's simply failing to render items (usually outside of your render distance), or from mismatched block states versus textures in my investigations.

**Comment by sakura-ryoko** [comment]
I leave the errors ON because the rendering system is a large and complex set of code, and still in need of additional debugging; but the problem is in most cases I cannot reproduce the issues that people are having.  Usually it's related to people's machines struggling to render the Overlays + everything else going on at once.  Perhaps you can also try reducing your Rendering Threads to 2 from the default of 4 if you have a slower machine.

**Comment by sakura-ryoko** [comment]
Other settings that could Improve performance: `renderThreadNoTimeout -> false`, or perhaps try temporarily disabling the Overlay Rendering to see if the 'rest' of the rendering system works fine.

`renderBlocksAsTranslucent` also takes a performance hit if enabled, for example; or if people try to 'tweak' their thread count too high.
